version: '3.8'

services:
  python_api:              # Service Name
    build: ./python-api    # <--- CORRECT INDENTATION (Directly under python_api)
    container_name: python_api_service
    ports:
      - "8000:8000"
    deploy:                # <--- Deploy section (Correct indentation)
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    networks:              # <--- Networks section (Correct indentation)
      - api_compare_net
    restart: unless-stopped

  rust_api:                # Service Name
    build: ./rust-api      # <--- CORRECT INDENTATION (Directly under rust_api)
    container_name: rust_api_service
    ports:
      - "8001:8001"
    deploy:                # <--- Deploy section (Correct indentation)
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    networks:              # <--- Networks section (Correct indentation)
      - api_compare_net
    restart: unless-stopped

networks:
  api_compare_net:
    driver: bridge